### ISSUE TITLE
4月26版 R4S还是没有核显  没有/dev/dri/renderD128

### ISSUE THREAD

**Issue by picasoul** [kiddin9/OpenWrt_x86-r2s-r4s-N1#672]
希望老大编译一版带核显的固件，期待：）

**Comment by genesis-lua** [comment]
测试i5-7500同没有核显，万兆速率仍是跑不满

**Comment by kiddin9** [comment]
05.02版已支持核显

![image](https://user-images.githubusercontent.com/48883331/166239325-cb2da13a-b7b8-4601-a3f7-11f18967105d.png)

**Comment by genesis-lua** [comment]
> 05.02版已支持核显
> 
> ![image](https://user-images.githubusercontent.com/48883331/166239325-cb2da13a-b7b8-4601-a3f7-11f18967105d.png)

牛逼（破音）

**Comment by picasoul** [comment]
这么快就支持了，大佬威武！
