### ISSUE TITLE
Newifi3 D2的5.19版本安装OpenClash直接崩溃了

### ISSUE THREAD

**Issue by dust2k** [kiddin9/OpenWrt_x86-r2s-r4s-N1#713]
因为bypass怎么都无法连接，我就直接删了bypass，然后从软件包里安装openClash，但是安装到一半，就说9.8空间已经占用了98%，然后报错，删除也没法删除，重启后管理界面都进不去，只能重刷。

**Comment by kiddin9** [comment]
D2只有32M,无法同时安装bypass和openclash,定制的时候只选择OpenClash应该装得下.

**Comment by dust2k** [comment]
我点了删除bypass，告诉我成功删除，但空间貌似没腾出来。。。估计还是不能像windows那样删除预装程序。。

**Comment by kiddin9** [comment]
出厂软件包删除也不会腾出空间, 只能通过在线定制 http://op.supes.top/ 去除.

**Comment by dust2k** [comment]
之前没有碰到过出厂的软件连不成功的，这是第一次，折腾了一下午，怎么都不行，干脆换一个试试，没想还崩了。。

**Comment by dust2k** [comment]
这个issue可以关了，确实是空间不够。。
