### ISSUE TITLE
MT系列的无线芯片据说不支持自动选频率，但是手动之后依然报错

### ISSUE THREAD

**Issue by dust2k** [kiddin9/OpenWrt_x86-r2s-r4s-N1#715]
我已经把2.4G和5G都选成了固定的，但依然报如下错误。。

Sun May 22 10:35:39 2022 daemon.notice hostapd: ACS: Survey is missing noise floor
Sun May 22 10:35:39 2022 daemon.notice hostapd: ACS: Survey is missing noise floor
Sun May 22 10:35:39 2022 daemon.notice hostapd: ACS: Survey is missing noise floor
Sun May 22 10:35:39 2022 daemon.notice hostapd: ACS: Survey is missing noise floor
Sun May 22 10:35:39 2022 daemon.notice hostapd: wlan0: ACS-COMPLETED freq=2447 channel=8

**Comment by kiddin9** [comment]
不要一直开issue刷屏,在同一个问题下回复就行了,我的AC2100是正常的,目前手上没有D2, 试试别改SSID,或者换个其他的SSID.

**Comment by dust2k** [comment]
这个两个不同的错误，我只是提供更多的细节给你判断问题的所在。。

**Comment by dust2k** [comment]
其实这个错误不影响2.4或者5G最终选定一个频道。。是auto造成的，算了，关了吧。。
