### ISSUE TITLE
默认版本卸载passby以后会上不了网

### ISSUE THREAD

**Issue by hasdlj3** [kiddin9/OpenWrt_x86-r2s-r4s-N1#720]
默认版本卸载passby以后会上不了网，显示找不到DNS错误，但是固件内连接软件源之类的都是正常的

**Comment by kiddin9** [comment]
不要卸载,卸载了也不会释放空间,

**Comment by DearTanker** [comment]
确实会这样，可以选择不移除依赖进行卸载就行了。
其实我觉得默认版本尽量能原味一点，插件都自己装比较好。
